import { createI18n } from 'vue-i18n'

export const i18n = createI18n({
  locale: 'en',
  globalInjection: true,
  messages: {
    en: {
      welcome: 'Welcome Back, {name}',
      pokeBerryTitle: 'Poke Berry',
      storeProductTitle: 'Store Product',
      action: 'Action',
      name: 'Name',
      url: 'URL',
      naturalGiftPower: 'Natural Gift Power',
      naturalGiftType: 'Natural Gift Type',
      size: 'Size',
      smoothness: 'Smoothness',
      soilDryness: 'Soil Dryness',
      title: 'Title',
      price: 'Price',
      description: 'Description',
      category: 'Category',
      rating: 'Rating',
      image: 'Image',
      value: 'Value',
      loadingData: 'Loading Data',
    },
    id: {
      welcome: 'Selamat Datang, {name}',
      pokeBerryTitle: 'Poke Berry',
      storeProductTitle: 'Produk Toko',
      action: 'Aksi',
      name: 'Nama',
      url: 'URL',
      naturalGiftPower: 'Kekuatan Alami',
      naturalGiftType: 'Tipe Hadiah Alami',
      size: 'Ukuran',
      smoothness: 'Kelembutan',
      soilDryness: 'Kekeringan Tanah',
      title: 'Judul',
      price: 'Harga',
      description: 'Deskripsi',
      category: 'Kategori',
      rating: 'Penilaian',
      image: 'Gambar',
      value: 'Nilai',
      loadingData: 'Memuatkan Informasi',
    },
  },
})
